name: Build Android APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew assembleDebug

      - name: Upload APKs
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-debug-apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            wear/build/outputs/apk/debug/wear-debug.apk
