name: Build APK

on:
  push:
    branches:
      - main  # Trigger build when there's a push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the runner environment

    steps:
    # Step 1: Checkout the code from your repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java Development Kit (JDK)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Ensure you're using a compatible Java version (e.g., JDK 11)

    # Step 3: Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2  # Setup Android SDK correctly
      with:
        sdk-version: '30.0.3'  # Define the SDK version (you can update this to match your requirements)
        ndk-version: '21.4.7075529'  # Optional: If you need NDK

    # Step 4: Install dependencies
    - name: Install dependencies
      run: ./gradlew dependencies --stacktrace

    # Step 5: Build APK (Release Build)
    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace  # Change to assembleDebug for debug APKs

    # Step 6: List files to confirm APK generation
    - name: List APK files in the output directory
      run: |
        echo "Listing APK files..."
        ls app/build/outputs/apk/release/

    # Step 7: Upload the release APK as an artifact
    - name: Upload Release APK artifact
      if: success() && contains(steps.list_apk.outputs.files, 'app-release.apk')
      uses: actions/upload-artifact@v3.1.2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk  # Correct path to the release APK

    # Step 8: Optional - Upload Debug APK artifact
    - name: Upload Debug APK artifact (optional)
      if: success() && contains(steps.list_apk.outputs.files, 'app-debug.apk')
      uses: actions/upload-artifact@v3.1.2
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk  # Correct path to the debug APK
