name: Build APK

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify Java version here (e.g., '11', '8', etc.)
          distribution: 'temurin'  # Use the temurin distribution (AdoptOpenJDK has been renamed)

      # Install Android SDK and required build tools
      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y android-sdk
          echo "y" | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "android-30"

      # Verify Gradle version (helpful for debugging)
      - name: Check Gradle version
        run: ./gradlew --version

      # Ensure gradlew file exists and is executable
      - name: Check gradlew file
        run: |
          ls -l ./gradlew  # Ensure gradlew is present
          chmod +x ./gradlew  # Ensure it's executable

      # Cache Gradle dependencies (optional but speeds up future builds)
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the APK using gradlew and print detailed logs with --stacktrace
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace  # Print detailed logs for debugging

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk  # Path to the generated APK
